from django.urls import path
from .import  views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
     path('beranda_1/',views.beranda_1, name='beranda_1'),
      path('siswa/kuis_bab1', views.kuis_bab1, name='kuis_bab1'),
       path('semua_kuis', views.semua_kuis, name='semua_kuis'),
    path('kuis<int:quiz_id>', views.kuis_view, name='kuis'), 
     path('soal_evaluasi<int:quiz_id>', views.soal_evaluasi, name='soal_evaluasi'), 
     path('hasil_kuis/<int:quiz_id>/', views.hasil_kuis, name='hasil_kuis'),
    path("program",views.program,name="program"), 
     path("bahasa_pemrograman",views.bahasa_pemrograman,name="bahasa_pemrograman"), 
     path("interpreter_compiler",views.interpreter_compiler,name="interpreter_compiler"), 
     path("bahasa_python",views.bahasa_python,name="bahasa_python"),
     path("program_sederhana",views.program_sederhana,name="program_sederhana"),
     path("kuis_bab1",views.kuis_bab1,name="kuis_bab1"),
     path("beranda2",views.beranda2,name="beranda2"), 
     path("tipe_data",views.tipe_data,name="tipe_data"), 
     path("variabel",views.variabel,name="variabel"), 
     path("operator",views.operator,name="operator"), 
     path("kuis_bab2",views.kuis_bab2,name="kuis_bab2"), 
     path("beranda3",views.beranda3,name="beranda3"), 
     path("percabangan",views.percabangan,name="percabangan"), 
     path("percabangan_if",views.percabangan_if,name="percabangan_if"), 
     path("percabangan_if_else",views.percabangan_if_else,name="percabangan_if_else"), 
     path("percabangan_elif",views.percabangan_elif,name="percabangan_elif"), 
     path("percabangan_bersarang",views.percabangan_bersarang,name="percabangan_bersarang"), 
     path("kuis_bab3",views.kuis_bab3,name="kuis_bab3"), 
     path("beranda4",views.beranda4,name="beranda4"), 
     path("perulangan",views.perulangan,name="perulangan"), 
     path("perulangan_while",views.perulangan_while,name="perulangan_while"), 
     path("perulangan_for",views.perulangan_for,name="perulangan_for"), 
     path("kuis_bab4",views.kuis_bab4,name="kuis_bab4"), 
     path("beranda5",views.beranda5,name="beranda5"),
     path("fungsi",views.fungsi,name="fungsi"),
     path("membuat_fungsi",views.membuat_fungsi,name="membuat_fungsi"),
     path("cara_kerja_fungsi",views.cara_kerja_fungsi,name="cara_kerja_fungsi"),
     path("parameterisasi_fungsi",views.parameterisasi_fungsi,name="parameterisasi_fungsi"),
     path("variabel_lokal_global",views.variabel_lokal_global,name="variabel_lokal_global"),
     path("parameter_formal_aktual",views.parameter_formal_aktual,name="parameter_formal_aktual"),
     path("parameter_wajib_opsional",views.parameter_wajib_opsional,name="parameter_wajib_opsional"),
     path("sintak_dasar",views.sintak_dasar,name="sintak_dasar"),
     path("komentar",views.komentar,name="komentar"),
     path("operator_perbandingan",views.operator_perbandingan,name="operator_perbandingan"),
     path("operator_penugasan",views.operator_penugasan,name="operator_penugasan"),
     path("operator_logika",views.operator_logika,name="operator_logika"),
     path("input",views.input,name="input"),
     path("output",views.output,name="output"),
     path("beranda3",views.beranda3,name="beranda3"),
     path("kuis_bab5",views.kuis_bab5,name="kuis_bab5"),
     path("beranda6",views.beranda6,name="beranda6"),
     path("kuis_bab6",views.kuis_bab6,name="kuis_bab6"),
     path("beranda7",views.beranda7,name="beranda7"),
     path("kuis_bab7",views.kuis_bab7,name="kuis_bab7"),
     path("evaluasi",views.evaluasi,name="evaluasi"),
     path("ending",views.ending,name="ending"),
         
]   

