# Generated by Django 5.0 on 2024-01-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akun", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siswa",
            name="kelas",
            field=models.CharField(
                choices=[("X", "X"), ("XI", "XI"), ("XII", "XII")], max_length=20
            ),
        ),
    ]
