# Generated by Django 5.0 on 2024-03-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akun", "0002_alter_siswa_kelas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siswa",
            name="kelas",
            field=models.CharField(
                choices=[
                    ("X MIPA 1", "X MIPA 1"),
                    ("X MIPA 2", "X MIPA 2"),
                    ("X MIPA 3", "X MIPA 3"),
                ],
                max_length=20,
            ),
        ),
    ]
