# Generated by Django 5.0 on 2024-01-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materi", "0002_alter_category_options_alter_category_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizsubmission",
            old_name="submitted_at",
            new_name="submitted_pada",
        ),
    ]
