# Generated by Django 5.0 on 2024-03-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materi", "0004_rename_submitted_pada_quizsubmission_submitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsubmission",
            name="durasi_pengerjaan",
            field=models.IntegerField(default=0),
        ),
    ]
