# Generated by Django 5.0 on 2024-03-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materi", "0005_quizsubmission_durasi_pengerjaan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizsubmission",
            name="durasi_pengerjaan",
        ),
    ]
